#!/usr/bin/env python3
"""Generate the secrets test fixture at run time.

The fixture has to contain values in real provider formats, because that is
exactly what find_secrets.py matches on. Committing such values trips GitHub
push protection and every other secret scanner pointed at this repository --
correctly, since a scanner cannot tell a deliberately fake key from a live one.

So the values are assembled from fragments here and written to a temporary file
during the test run. Nothing secret-shaped is ever stored in git, and the
patterns still get exercised end to end.

Usage: make_secrets_fixture.py <output.js>
"""

import sys

# Split so no complete provider-format token exists as a literal in this file.
AWS = "AKIA" + "IOSFODNN7" + "EXAMPLE"
GH = "ghp_" + "1234567890abcdefghij" + "klmnopqrstuvwxyz"
STRIPE = "sk_" + "live_" + "51H8xKfL2eZvKYlo2CabcdEFGH"
GOOGLE = "AIza" + "SyD-9tSrke72PouQMnMX-a7eZSW0jkFMBWY"
MONGO = "mongodb+srv://" + "svcuser" + ":" + "S3cr3tP%40ss" + "@cluster0.abcde.mongodb.net/prod"
# alg=none, role=admin, exp in the past -- exercises the JWT decoder's notes.
JWT = (".".join([
    "eyJhbGciOiJub25lIiwidHlwIjoiSldUIn0",
    "eyJzdWIiOiIxMjM0IiwibmFtZSI6IkFkbWluIiwicm9sZSI6ImFkbWluIiwiZXhwIjoxNzAwMDAwMDAwfQ",
    "",
]))

TEMPLATE = """// Fixture: a mix of real-shaped secrets, placeholders and minified noise.
// Generated by make_secrets_fixture.py -- not committed, see that file for why.
var cfg = {{
  awsKey: "{aws}",
  githubToken: "{gh}",
  stripe: "{stripe}",
  googleMaps: "{google}",
  apiKey: "YOUR_API_KEY_HERE",
  api_key: "${{process.env.API_KEY}}",
  clientSecret: "changeme",
  password: "Hunter2!Winter2024",
  sessionToken: "a7Kd93JfLp0QzXcV2mNbT8yRw5Es1UiO",
  debug: true,
  locale: "en-US",
  mime: "application/json"
}};
var conn = "{mongo}";
var jwt = "{jwt}";
var api = "https://payments.internal.corp.example/v1/charge";
var admin = "https://10.20.30.40:8443/admin";
fetch('/api/v1/orders?status=pending&limit=50');
//# sourceMappingURL=app.bundle.js.map
"""


def main():
    if len(sys.argv) != 2:
        print(__doc__.strip().splitlines()[-1], file=sys.stderr)
        return 2
    with open(sys.argv[1], "w", encoding="utf-8") as fh:
        fh.write(TEMPLATE.format(aws=AWS, gh=GH, stripe=STRIPE, google=GOOGLE,
                                 mongo=MONGO, jwt=JWT))
    return 0


if __name__ == "__main__":
    sys.exit(main())
